import { FedexConfig } from "../../config";
import { configureFedexClient } from "../clientFactory";
import { FedexShipSdk } from "./generated/index";

/**
 * High-level client for the FedEx Ship API v1.
 * * This class orchestrates the creation of shipping labels and shipments. 
 * It abstracts the complex OAuth2 handshake and provides a typed interface 
 * for the generated FedEx Ship SDK, ensuring thread-safe execution within 
 * a multi-tenant library environment.
 * * @example
 * ```typescript
 * const shipClient = createFedexShipClient(config);
 * await shipClient.init();
 * const label = await shipClient.createLabel(shipmentRequest);
 * ```
 */
export class FedexShipClient {
  /** * Internal instance of the generated FedEx Ship SDK.
   * Maintains isolated request configuration including the Bearer token.
   */
  private sdk: FedexShipSdk;

  /**
   * Initializes a new instance of the FedexShipClient.
   * * @param config - FedEx configuration containing clientId, clientSecret, and account number.
   */
  constructor(private config: FedexConfig) {
    /**
     * Initialize the SDK with the configured base URL.
     * Defaults to the production API if not specified in the config.
     */
    this.sdk = new FedexShipSdk({
      BASE: config.baseUrl || "https://apis.fedex.com",
    });
  }

  /**
   * Performs the OAuth2 handshake to authorize the shipment session.
   * * Fetches a scoped access token from FedEx and injects it into the 
   * internal SDK configuration. This must be called before any 
   * label generation attempts.
   * * @throws {ShipstackError} If credentials are invalid or the auth service is down.
   * @returns {Promise<void>}
   */
  async init(): Promise<void> {
    /**
     * We pass the specific SDK instance's configuration to the factory 
     * to ensure local state management and prevent credential leakage.
     */
    await configureFedexClient(this.sdk.request.config, "Ship");
  }

  /**
   * Generates a shipping label and creates a shipment record in the FedEx system.
   * * Maps to the 'POST /ship/v1/shipments' endpoint. This method requires 
   * a fully formed FedEx shipment object, typically generated by a 
   * Request Builder.
   * * @param requestBody - The raw FedEx 'Full_Schema_Shipment' payload.
   * @returns {Promise<any>} The raw FedEx shipment response including label image data.
   */
  async createLabel(requestBody: any): Promise<any> {
    /**
     * Retrieve the token from the instance-specific configuration 
     * managed during the init() call.
     */
    const token = this.sdk.request.config.TOKEN;

    return this.sdk.default.createShipment(
      "application/json",        // contentType
      `Bearer ${token}`,         // authorization
      requestBody
    );
  }
}

/**
 * Factory function to instantiate a new FedexShipClient.
 * * @param config - The validated FedEx configuration object.
 * @returns An initialized instance of FedexShipClient ready for label generation.
 */
export const createFedexShipClient = (config: FedexConfig): FedexShipClient =>
  new FedexShipClient(config);